spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crypto_comm?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      #ddl-auto: update
    #show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: pWJMjp3tEE3RNgZFiiuoQ33DSADWEQ
  expiration: 3600000
logging:
  level:
    org.springframework.security: DEBUG